name: CI with Verilator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  CI_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Verilator
      run: |
        sudo apt-get update
        sudo apt-get install -y verilator g++ make
        sudo apt-get install help2man perl python3
        sudo apt-get install libfl2
        sudo apt-get install libfl-dev
        sudo apt-get install zlib1g zlib1g-dev
        sudo apt-get install ccache
        sudo apt-get install mold
        sudo apt-get install libgoogle-perftools-dev numactl
        sudo apt-get install perl-doc
        sudo apt-get install git autoconf flex bison
        
    - name: Generate filelist
      run: |
        find . -name "*.sv" -o -name "*.vh" > All_filesList.f
        cat All_filesList.f

    - name: Lint all files
      run: verilator --lint-only -f All_filesList.f --timing -Wno-MULTITOP -I./src/logphy -I./tb/logphy -I./src/logphy/LTSM
        
    - name: MB_RX test
      run: |
        verilator -I./tb/logphy -I./src/logphy -I./src/logphy/LTSM --binary -f All_filesList.f --top-module MB_RX_tb --trace --timing --trace-max-array 512 --trace-max-width 512 --timescale 1ps/1ps 
        ./obj_dir/VMB_RX_tb

    - name: MB RX-to-TX test
      run: |
        verilator -I./tb/logphy -I./src/logphy -I./src/logphy/LTSM --binary -f All_filesList.f --top-module MB_tb --trace --timing --trace-max-array 512 --trace-max-width 512 --timescale 1ps/1ps 
        ./obj_dir/VMB_tb

    - name: Sideband TX-RX test
      run: |
        verilator -I./tb/logphy -I./src/logphy -I./src/logphy/LTSM --binary -f All_filesList.f --top-module SB_tb --trace --timing --trace-max-array 512 --trace-max-width 512 --timescale 1ns/1ps 
        ./obj_dir/VSB_tb

    #This test is a bit redundant, already tested in the following one with all the states of the link initialization
    #- name: LTSM SBINIT test
    #  run: |
    #    verilator -I./tb/logphy -I./src/logphy -I./src/logphy/LTSM --binary -f All_filesList.f --top-module LTSM_SBINIT_tb --trace --timing --trace-max-array 512 --trace-max-width 512 --timescale 1ns/1ps 
    #    ./obj_dir/VLTSM_SBINIT_tb

    - name: LTSM test
      run: |
        verilator -I./tb/logphy -I./src/logphy -I./src/logphy/LTSM --binary -f All_filesList.f --top-module LTSM_tb --trace --timing --trace-max-array 512 --trace-max-width 512 --timescale 1ns/1ps 
        ./obj_dir/VLTSM_tb


